source "https://rubygems.org"
ruby File.read("#{__dir__}/.ruby-version")

gemspec

gem "rake"

group :development do
  gem "foob"
  gem "foobara-command-generator"
  gem "foobara-domain-generator"
  gem "foobara-empty-ruby-project-generator"
  gem "foobara-files-generator"
  gem "foobara-organization-generator"
  gem "foobara-rubocop-rules"
  gem "guard-rspec"
  gem "rubocop-rake"
  gem "rubocop-rspec"
end

group :development, :test do
  gem "pry"
  gem "pry-byebug"
end

group :test do
  gem "foobara-spec-helpers", github: "foobara/spec-helpers"
  gem "rspec"
  gem "rspec-its"
  gem "simplecov"
end
